import Footer from './footer';
import './globals.css';
import Header from './header';
import Providers from './providers';

export const metadata = {
    title: 'Never bitcoin pledge',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html>
            <head />
            <body>
                <main className='flex min-h-screen flex-col items-center bg-gray-200'>
                    <div className='mx-2 mt-8 grid grid-cols-6 gap-x-2 gap-y-3 md:max-w-lg'>
                        <Providers>
                            <Header />
                            {children}
                            <Footer />
                        </Providers>
                    </div>
                </main>
            </body>
        </html>
    );
}
